### ISSUE TITLE
Tile based homepage top section

### ISSUE THREAD

**Issue by mglobel** [buzzbell/rapashwednesday#1]
Things needed
- [x] bandcamp embed
- [x] fourth tile content (I forgot some of our ideas for the fourth tile?)

From convo with ashwednesday, something like this:
<img width="784" alt="screen shot 2017-09-10 at 2 28 50 pm" src="https://user-images.githubusercontent.com/3036915/30252259-7146644e-9634-11e7-8029-690604447a59.png">

**Comment by mglobel** [comment]
yo @ashwednesday, do you have a bandcamp account yet? checking out their embed stuff, looks like they have alot of options: https://daily.bandcamp.com/2013/06/12/all-new-players-up-twitter-too/

**Comment by ashwednesday** [comment]
hey; yes i got a bandcamp account but nothing is posted there yet. would you like the log in credentials?

[](https://ashwednesday.bandcamp.com/)

**Comment by ashwednesday** [comment]
https://ashwednesday.bandcamp.com/

**Comment by mglobel** [comment]
@ashwednesday hmm, yeah looks like ill need to login for embed stuff. do they let u add members to your bandcamp? otherwise can email over some login credentials

**Comment by mglobel** [comment]
actually nvm, found the embed part! when do u plan on adding content to bandcamp?

**Comment by ashwednesday** [comment]
hey! o i see this new git hub now

the record is being mastered and should be ready to add to bandcamp this time next week

**Comment by ashwednesday** [comment]
re: forth tile content - i think we should stick with 2 tiles. left tile for the face pic/album cover and right tile for the bandcamp embed. below these two tiles let's have spotify/apple music/tidal/etc icons that link to my music on those platforms

"about" and "shows" could stay where they are or they could move to their own pages. we'd keep their links in the top right corner 

![4 tiles](https://user-images.githubusercontent.com/22849666/30666627-95467878-9e1a-11e7-9536-b466b82f20d7.jpg)

**Comment by mglobel** [comment]
Updated!
