### ISSUE TITLE
Onboard @ashwednesday

### ISSUE THREAD

**Issue by mglobel** [buzzbell/rapashwednesday#4]
## To Do
- [x] Fix the typo in the title on https://rapashwednesday-buzzbell-redesign.netlify.com/ by using the editor at
https://app.storyblok.com/#!/me/spaces/40969/stories/50534
`hint: title should say Ash Wednesday`
- [x] publish story to  https://rapashwednesday-buzzbell-redesign.netlify.com/
- [x] 🎉 🍄 🎵

**Comment by ashwednesday** [comment]
i think i did the fix!

**Comment by mglobel** [comment]
Yeehaw! :cowboy_hat_face: Looks like the text is changed in the editor, but hasn't been published:
 https://app.storyblok.com/#!/me/spaces/40969/stories/50534, Just one more step though to fully wrangle this 🐮 , and have changes show up on [new rapashwednesday.com](https://rapashwednesday-buzzbell-redesign.netlify.com/)
<img width="829" alt="screen shot 2017-09-15 at 2 21 08 pm" src="https://user-images.githubusercontent.com/3036915/30499740-596cf252-9a21-11e7-80cb-f651f2d23a29.png">

**Comment by ashwednesday** [comment]
ok i published some changes! does that make me officially on-boarded?

**Comment by mglobel** [comment]
hooray, officially onboarded! im visiting home this weekend and week, so should have plenty of time to finish the relaunch
