### ISSUE TITLE
embed new record 

### ISSUE THREAD

**Issue by ashwednesday** [buzzbell/rapashwednesday#5]
ayo! we're posted to bandcamp @ http://ashwednesday.bandcamp.com/album/turn-the-world-to-ash

you were able to get to the embed information yourself yea? below is a couple options for how the player could look on the site. i like the large art better, but i think the small style art will fit our box style more easily

speaking of the two boxes -- i'm imagining they will be this:

top left: album cover 
top right: album embed with small style art

for reference the album cover art is not quite done; there's going to be an image laid behind the writing. we can post it as is for now, and i'll send the updated version when it's ready 

<img width="969" alt="ttwtash bandcamp player small art" src="https://user-images.githubusercontent.com/22849666/30868729-109ea6b0-a2a5-11e7-9385-081213532f33.png">
<img width="1013" alt="ttwtash bandcamp player big art" src="https://user-images.githubusercontent.com/22849666/30868728-109dd4f6-a2a5-11e7-9bc4-925c2c6da74c.png">

![turn the world to ash](https://user-images.githubusercontent.com/22849666/30869398-9c13510e-a2a6-11e7-87d3-58ad43981add.png)

**Comment by ashwednesday** [comment]
@mglobel 

i can't figure out how to assign you in the "assignee" section; on the old git it allowed me to click there and add you

**Comment by mglobel** [comment]
@ashwednesday I changed your permissions i think you should be able to assign now..

But next time, bandcamp embed up!

https://rapashwednesday.com/home
